#!/usr/bin/env node
/**
 * Extract client CSS/JS from server.mjs as **evaluated** template strings
 * (what Node embeds into HTML), never raw backtick source bodies.
 *
 *   node scripts/extract_client_js.mjs
 */
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const SRC = fs.readFileSync(path.join(ROOT, "server.mjs"), "utf8");
const OUT = path.join(ROOT, "priv", "static");

/** Return source of a full `...` template literal starting at backtickIndex (inclusive). */
function extractLiteralSource(src, backtickIndex) {
  if (src[backtickIndex] !== "`") throw new Error("expected ` at " + backtickIndex);
  let i = backtickIndex + 1;
  let inExpr = false;
  let exprBrace = 0;
  while (i < src.length) {
    const c = src[i];
    if (!inExpr) {
      if (c === "\\") {
        i += 2;
        continue;
      }
      if (c === "`") return src.slice(backtickIndex, i + 1);
      if (c === "$" && src[i + 1] === "{") {
        inExpr = true;
        exprBrace = 1;
        i += 2;
        continue;
      }
      i++;
      continue;
    }
    if (c === "\\") {
      i += 2;
      continue;
    }
    if (c === "{") exprBrace++;
    else if (c === "}") {
      exprBrace--;
      if (exprBrace === 0) inExpr = false;
    }
    i++;
  }
  throw new Error("unterminated template at " + backtickIndex);
}

function evalLiteralSource(literal, sandbox = {}) {
  return vm.runInNewContext(literal, sandbox, { timeout: 10000 });
}

function evalConst(name) {
  const marker = `const ${name} = \``;
  const start = SRC.indexOf(marker);
  if (start < 0) throw new Error("missing const " + name);
  const bt = start + `const ${name} = `.length;
  return evalLiteralSource(extractLiteralSource(SRC, bt));
}

function write(name, body) {
  const dest = path.join(OUT, name);
  let text = String(body).replace(/^\n+/, "").replace(/\n*$/, "\n");
  // Never put CSS/JS /* banners */ into HTML fragments inlined into <head> (they render as text).
  if (!name.endsWith(".html")) {
    text =
      "/* generated by scripts/extract_client_js.mjs — re-run extractor; do not hand-fix escapes */\n" +
      text;
  }
  fs.writeFileSync(dest, text);
  console.log("wrote", name, text.length);
}

function firstScript(html) {
  const m = String(html).match(/<script>([\s\S]*?)<\/script>/i);
  if (!m) throw new Error("no <script> in html chunk");
  return m[1].replace(/^\n+/, "").replace(/\n+$/, "") + "\n";
}

function esc(s) {
  return String(s ?? "").replace(/[&<>"']/g, (c) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c],
  );
}

function editorSandbox() {
  const scope = {
    slug: "jhn.3.16",
    kind: "verse",
    osis: "JHN.3.16",
    parsed: {
      start: { book: "JHN", chapter: 3, verse: 16 },
      end: { book: "JHN", chapter: 3, verse: 16 },
    },
  };
  return {
    OUTLINER_JS: "",
    scope,
    note: null,
    rel: { contains: [], within: [], overlaps: [] },
    display: "John 3:16",
    locked: false,
    initial: [{ id: "b_new", indent: 0, text: "" }],
    atts: [],
    cipherJson: "null",
    sections: [],
    u: (p) => p,
    esc,
    escHtml: esc,
    cryptoBarHtml: () => "",
    relatedSection: () => "",
    renderAttachmentsBoard: () => "",
    blocksJson: (b) => JSON.stringify(b || []),
    isEncryptedNote: () => false,
    formatPassageForDisplay: () => "John 3:16",
    JSON,
    String,
    Number,
    Math,
  };
}

function readerSandbox() {
  const scope = {
    slug: "jhn.3",
    kind: "chapter",
    osis: "JHN.3",
    parsed: {
      start: { book: "JHN", chapter: 3 },
      end: { book: "JHN", chapter: 3 },
    },
  };
  return {
    OUTLINER_JS: "",
    scope,
    chapterScope: scope,
    display: "John 3",
    chapterNote: null,
    rows: "",
    seed: {},
    u: (p) => p,
    esc,
    escHtml: esc,
    blocksJson: (b) => JSON.stringify(b || {}),
    readerNoteHtml: () => "",
    formatPassageForDisplay: () => "John 3",
    isEncryptedNote: () => false,
    JSON,
    String,
    Number,
    Math,
  };
}

function findReturnTemplate(fnName) {
  const fnStart = SRC.indexOf(fnName);
  if (fnStart < 0) throw new Error("missing " + fnName);
  const ret = SRC.indexOf("return `", fnStart);
  if (ret < 0 || ret > fnStart + 8000) throw new Error("return template not found for " + fnName);
  return ret + "return ".length;
}

function findPageTemplate(fnMarker, mustInclude) {
  const fnStart = SRC.indexOf(fnMarker);
  if (fnStart < 0) throw new Error("missing " + fnMarker);
  let search = fnStart;
  while (true) {
    const idx = SRC.indexOf("return page(", search);
    if (idx < 0 || idx > fnStart + 35000) break;
    const bt = SRC.indexOf("`", idx);
    try {
      const lit = extractLiteralSource(SRC, bt);
      if (mustInclude.every((s) => lit.includes(s))) return bt;
    } catch {
      /* continue */
    }
    search = idx + 1;
  }
  throw new Error("page template not found for " + fnMarker);
}

// --- extract ---
fs.mkdirSync(OUT, { recursive: true });
fs.mkdirSync(path.join(OUT, "icons"), { recursive: true });

// app.css + pwa-head are managed in priv/static (theme dual-mode, modern chrome).
// server.mjs CSS is legacy/stale — do not clobber unless EXTRACT_CSS=1.
if (process.env.EXTRACT_CSS === "1") {
  write("app.css", evalConst("CSS"));
  write("pwa-head.html", evalConst("PWA_HEAD"));
  console.log("extract_client_js: wrote app.css + pwa-head (EXTRACT_CSS=1)");
} else {
  console.log(
    "extract_client_js: skipping app.css + pwa-head (priv/static is SOT; set EXTRACT_CSS=1 to overwrite from server.mjs)",
  );
}
write(
  "outliner.js",
  evalConst("OUTLINER_JS") +
    "\nif (typeof mountOutliner === 'function') window.mountOutliner = mountOutliner;\n",
);
write("crypto.js", evalConst("CRYPTO_JS"));
write("pwa-boot.js", evalConst("PWA_BOOT_JS"));

// door-share
{
  const bt = findReturnTemplate("function doorShareChipHtml");
  const lit = extractLiteralSource(SRC, bt);
  const html = evalLiteralSource(lit, {
    DOOR_OPEN: false,
    door: () => "example-door-key",
    keyLabel: esc("example-door-key"),
    esc,
  });
  let script = firstScript(html);
  script = script.replace(
    /var key = ("(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*');/,
    'var key = document.getElementById("door-share").getAttribute("data-key");',
  );
  write("door-share.js", script);
}

// crypto-bar
{
  const bt = findReturnTemplate("function cryptoBarHtml");
  const lit = extractLiteralSource(SRC, bt);
  const html = evalLiteralSource(lit, { locked: false });
  write("crypto-bar.js", firstScript(html));
}

// ref-search
{
  const bt = findReturnTemplate("function refSearchHtml");
  const lit = extractLiteralSource(SRC, bt);
  const html = evalLiteralSource(lit, { u: (p) => p, esc });
  write("ref-search.js", firstScript(html));
}

// home-tree
{
  const bt = findReturnTemplate("function renderHomeNoteTree");
  const lit = extractLiteralSource(SRC, bt);
  const html = evalLiteralSource(lit, {
    body: "",
    u: (p) => p,
    esc,
    renderHomeTreeNode: () => "",
  });
  write("home-tree.js", firstScript(html));
}

// editor-page
{
  const bt = findPageTemplate("function renderEditor(scope, note, rel)", ["OUTLINER_JS", "initial-blocks"]);
  const lit = extractLiteralSource(SRC, bt);
  const html = evalLiteralSource(lit, editorSandbox());
  let script = firstScript(html);
  script = script.replace(
    /const slug = ("(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*');/,
    'const slug = JSON.parse(document.getElementById("page-meta").textContent).slug;',
  );
  write("editor-page.js", script);
}

// reader-page
{
  const bt = findPageTemplate("async function renderRead(scope)", ["expand-notes"]);
  const lit = extractLiteralSource(SRC, bt);
  const html = evalLiteralSource(lit, readerSandbox());
  let script = firstScript(html);
  script =
    'const META = JSON.parse(document.getElementById("page-meta").textContent);\n' + script;
  script = script.replace(
    /const chapterDisplay = ("(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*');/,
    "const chapterDisplay = META.display;",
  );
  write("reader-page.js", script);
}

// public assets
const pub = path.join(ROOT, "public");
if (fs.existsSync(path.join(pub, "sw.js"))) {
  fs.copyFileSync(path.join(pub, "sw.js"), path.join(OUT, "sw.js"));
  console.log("copied sw.js");
}
const icons = path.join(pub, "icons");
if (fs.existsSync(icons)) {
  for (const f of fs.readdirSync(icons)) {
    fs.copyFileSync(path.join(icons, f), path.join(OUT, "icons", f));
  }
  console.log("copied icons");
}

// syntax gate
let failed = 0;
for (const f of fs.readdirSync(OUT)) {
  if (!f.endsWith(".js")) continue;
  const file = path.join(OUT, f);
  const r = spawnSync(process.execPath, ["--check", file], { encoding: "utf8" });
  if (r.status !== 0) {
    console.error("SYNTAX FAIL", f, r.stderr || r.stdout);
    failed++;
  } else {
    console.log("syntax ok", f);
  }
}
if (failed) {
  console.error("extract_client_js failed:", failed);
  process.exit(1);
}
console.log("extract_client_js: done");
