[phases.setup]
nixPkgs = ["elixir", "erlang"]

[phases.install]
cmds = [
  "mix local.hex --force",
  "mix local.rebar --force",
  "MIX_ENV=prod mix deps.get --only prod"
]

[phases.build]
cmds = [
  "MIX_ENV=prod mix compile",
  "MIX_ENV=prod mix release"
]

[start]
cmd = "/app/_build/prod/rel/keyverse/bin/keyverse start"
